/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cryptowallet;

import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import org.json.simple.JSONObject;
import org.json.simple.JSONArray;

/**
 *
 * @author marc
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    
    public class userDataObj{
        public String Title;
        public String data;
        public boolean hidden;
    }
    
    private CryptoWalletDB walletDB;
    private Map<String,String> dataMap;
    
    public MainFrame(CryptoWalletDB database) {
        initComponents();
       
        walletDB=database;
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        
        //decrypt the database
        JSONObject jsonObj;
        try{
            jsonObj=walletDB.decryptDatabase();
            dataMap=(Map<String,String>)jsonObj;
            displayGroups(dataMap);
            
        
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage(),"Cryptowallet Message",
                        JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void displayGroups(Map<String,String> dataMap){
        DefaultListModel model = new DefaultListModel();
        for(String group:dataMap.keySet()){
            model.addElement(group);
        }
        groupList.setModel(model);
    }
    
    //----------------------------------------------------------------------
    //get current group select and display the items in the selected group
    //----------------------------------------------------------------------
    private void displayItemList(){
        String selectedGroup=(String)groupList.getSelectedValue();
        DefaultListModel model = new DefaultListModel();
        Object obj = dataMap.get(selectedGroup);
        JSONArray jsonArray = (JSONArray)obj;
        for(int n=0;n<jsonArray.size();n++){
            Map<String,String> itemMap = (Map<String,String>)jsonArray.get(n);
            
            for(String itemName:itemMap.keySet()){
                model.addElement(itemName);
            }
        }
        
        itemList.setModel(model);
                   
    }
    
   

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        groupList = new javax.swing.JList();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemList = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crypto Wallet");

        jScrollPane2.setMinimumSize(new java.awt.Dimension(200, 22));

        groupList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        groupList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                groupListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(groupList);

        jSplitPane1.setLeftComponent(jScrollPane2);

        itemList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(itemList);

        jSplitPane1.setRightComponent(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void groupListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_groupListMouseClicked
        displayItemList();
    }//GEN-LAST:event_groupListMouseClicked

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList groupList;
    private javax.swing.JList itemList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
